/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fcm.empleados;

import java.io.IOException;
import javafx.application.Application;
import static javafx.application.Application.launch;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;

import javafx.stage.Stage;

/**
 * Plantilla JAVAFX
 * Autor:
 * Curso y año:
 * Objetivo de esta clase:
 */
public class Main extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws IOException {
        FXMLLoader root = new FXMLLoader(getClass().getResource("Empleados.fxml"));
        
        Scene scene=new Scene(root.load());
        Stage escenaPrincipal = primaryStage;
        escenaPrincipal.setScene(scene);
        escenaPrincipal.setTitle("Empleados");
        //Se carga el controlador del archivo fxml para poder llamar a sus funciones públicas
        controllerEmpleados controlador = root.getController();
        //Se define la acción a realizar en el cierre de la app
        escenaPrincipal.setOnCloseRequest(event -> {
            //Se llama al mérodo "guardar" de la clase controllerEmpleados
            controlador.guardar();
        });
        escenaPrincipal.show();
    }

}
